### ISSUE TITLE
Hello, thank you very much. Can't the robot automatically replenish energy and repair

### ISSUE THREAD

**Issue by cnscdh** [srisaard/wax-farm-bot#1]

**Comment by cnscdh** [comment]
Transaction Results
Cannot read properties of undefined (reading 'actions'){"transaction_id":"33b8dc1d5b270128ec2c6c2a53d15842878defc5deb96a8c87439a5ccb40e0","processed":{"id":"33bc1d5b270128ec2c6c2a53d15842875e8defc5deb7439a5ccb40e0","block_num":152389440,"block_time":"2021-11-23T06:27:12.500","producer_block_id":null,"receipt":{"status":"executed","cpu_usage_us":819,"net_usage_words":16},"elapsed":819,"net_usage":128,"scheduled":false,"action_traces":[{"action_ordinal":1,"creator_action_ordinal":0,"closest_unnotified_ancestor_action_ordinal":0,"receipt":{"receiver":"farmersworld","act_digest":"955551227cf49c2f6bd08e38cea5e5317b70d8a646f5ae7431100ab5","global_sequence":"28295077515","recv_sequence":117280242,"auth_sequence":[["slmme.wam",1245]],"code_sequence":81,"abi_sequence":20},"receiver":"farmersworld","act":{"account":"farmersworld","name":"claim","authorization":[{"actor":"slmme.wam","permission":"active"}],"data":{"owner":"slmme.wam","asset_id":"1099575440343"},"hex_data":"00009086575c4ed20300010000"},"context_free":false,"elapsed":368,"console":"","trx_id":"33b8dc1d5b27012c6c2a53d15842875deb96a8c87439a5ccb40e0","block_num":152389440,"block_time":"2021-11-23T06:27:12.500","producer_block_id":null,"account_ram_deltas":[],"account_disk_deltas":[],"except":null,"error_code":null,"return_value_hex_data":"","inline_traces":[{"action_ordinal":2,"creator_action_ordinal":1,"closest_unnotified_ancestor_action_ordinal":1,"receipt":{"receiver":"farmersworld","act_digest":"6e75206b7d522bb385aff7c2d92377dffc5d03af11d3243f28f5eb","global_sequence":"28295077516","recv_sequence":117280243,"auth_sequence":[["farmersworld",83674472]],"code_sequence":81,"abi_sequence":20},"receiver":"farmersworld","act":{"account":"farmersworld","name":"logbonus","authorization":[{"actor":"farmersworld","permission":"active"}],"data":{"asset_owner":"slmme.wam","bonus_rewards":["0.0000 WOOD"]},"hex_data":"000090860575c40100000000000004574f4f400000"},"context_free":false,"elapsed":31,"console":"","trx_id":"33b8dc1d5b270128ec2c6c2a53d15842e8defc5deb96a8c87439a5ccb40e0","block_num":152440,"block_time":"2021-11-23T06:27:12.500","producer_block_id":null,"account_ram_deltas":[],"account_disk_deltas":[],"except":null,"error_code":null,"return_value_hex_data":"","inline_traces":[]},{"action_ordinal":3,"creator_action_ordinal":1,"closest_unnotified_ancestor_action_ordinal":1,"receipt":{"receiver":"farmersworld","act_digest":"29f0ad8f2f9bc21ef497514e8563a9530e798f29b6c9fa68","global_sequence":"28295077517","recv_sequence":117280244,"auth_sequence":[["farmersworld",83674473]],"code_sequence":81,"abi_sequence":20},"receiver":"farmersworld","act":{"account":"farmersworld","name":"logclaim","authorization":[{"actor":"farmersworld","permission":"active"}],"data":{"asset_owner":"slmme.wam","asset_id":"10995770343","rewards":["50.8194 WOOD"]},"hex_data":"0000908603e575c4e7bcd203000122c107000000000004574f4f44000000"},"context_free":false,"elapsed":25,"console":"","trx_id":"33b8dc1d5b270128ec2c6c2a53d15842875e8defc5deb96a8c87439a5ccb40e0","block_num":152389440,"block_time":"2021-11-23T06:27:12.500","producer_block_id":null,"account_ram_deltas":[],"account_disk_deltas":[],"except":null,"error_code":null,"return_value_hex_data":"","inline_traces":[]}]}],"account_ram_delta":null,"except":null,"error_code":null}}

**Comment by srisaard** [comment]
Done, please feedback if it works

**Comment by cnscdh** [comment]
thank，It would be better if automatic replenishment and automatic repair were added！
Can farmingtales be used normally
