### ISSUE TITLE
officeland does not work

### ISSUE THREAD

**Issue by softweri** [srisaard/wax-farm-bot#13]
(index):1061 Uncaught (in promise) TypeError: Cannot read property 'claim_datas' of undefined
    at Officeland_task ((index):1061)

Does not work, I do not understand th
![Screenshot_3](https://user-images.githubusercontent.com/5292472/151717031-c833e3e2-c562-4edb-a4db-597d28b865ff.png)
e reason! You can tell the settings in the instructions.

**Comment by srisaard** [comment]
Do you have a officeland NFT?
If not, please unchecked the officeland checkbox.
