### ISSUE TITLE
Is this working with OfficeLand ?

### ISSUE THREAD

**Issue by Ankor12** [srisaard/wax-farm-bot#14]
Hello, your script is awesome with Farmers World, thank you !
But i dont get it working with OfficeLand.
Is this still working ? Or maybe i am missing something ?

Ok i just checked and it's conencted, so no problem

**Comment by srisaard** [comment]
Just update to support new patch.

**Comment by Ankor12** [comment]
I updated, but its strange, sometimes i see my NFT, and since i closed here, i dont see them anymore

**Comment by srisaard** [comment]
Did you moved to new office? Since, Dev update their contract, many thing still unstable.

**Comment by Ankor12** [comment]
Yes i moved my account 
I see only this menu https://imgur.com/jdGmsyf

EDIT : its working now, thank you <3
