### ISSUE TITLE
Cannot read properties of undefined (reading 'rpc')

### ISSUE THREAD

**Issue by Ankor12** [srisaard/wax-farm-bot#16]
Hello, i think they changed something on farmersworld,
Transaction results Cannot read properties of undefined (reading 'rpc')

**Comment by beomsookim1020** [comment]
I got the same problem.
no solution?

**Comment by srisaard** [comment]
Can you tell me how to reproduce the problem? I can run it properly without a problem.

**Comment by Ankor12** [comment]
It was a temporary problem, everything works perfectly now.
Thank you!

**Comment by srisaard** [comment]
Nice, I will add more RPC ( 10 in totals for new update )

**Comment by Ankor12** [comment]
Thank you
