### ISSUE TITLE
Add auto-feed animals?

### ISSUE THREAD

**Issue by Tabakfeld** [srisaard/wax-farm-bot#17]
Hey :)
is there a way to add auto-feed animals such as Cows, Chicken...?
Thanks for the farming bot

**Comment by srisaard** [comment]
Please try animal claim feature, I don't own any animal so please feedback if it don't work properly

**Comment by Tabakfeld** [comment]
Thx man <3, im testing it. There is an animal bug tho atm on farmersworld side, so testing might take a while, until they fix it.  

Edit: Atm it gives me "missing anmclaim.animal_id (type=uint64)" for my cow

**Comment by Ankor12** [comment]
hello, any update here ?
Thank you @srisaard  <3

**Comment by srisaard** [comment]
Sorry for let you wait so long, now there is solved.
