### ISSUE TITLE
I don't want to show other games

### ISSUE THREAD

**Issue by piqihaha** [srisaard/wax-farm-bot#22]
I commented out the game code that I don't want to show, but it doesn't continue. How to do this
![12](https://user-images.githubusercontent.com/25221169/155997700-a9bb4df6-4b6f-4107-8c6f-0198387ec00a.png)
![13](https://user-images.githubusercontent.com/25221169/155997724-fb48dbbc-5b69-4b22-b9da-98339d7608f3.png)

**Comment by Ankor12** [comment]
You just have to uncheck the box of the games you don't want
