### ISSUE TITLE
Farmersworld Tokens

### ISSUE THREAD

**Issue by ghostprize** [srisaard/wax-farm-bot#4]
![1641452428945](https://user-images.githubusercontent.com/95231293/148466066-b2221c7a-ca4f-485e-98a3-06367503e609.jpg)

Equipment repairs or food refills are not available for accounts with different currency positions.
ex: const current_gold = balance.balances[2].split(" ")[0];

i use for mornitor my account
I'm not good at coding Please help fix this request.

			substringG = "GOLD"
			substringW = "WOOD"
			substringF = "FOOD"
			
			if (token_0.includes(substringG) === true){
				var token_G = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[0]).slice(0,-5))
				console.log(token_G);
			}
			if (token_0.includes(substringW) === true){
				var token_W = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[0]).slice(0,-5))
				console.log(token_W);
			}
			if (token_0.includes(substringF) === true){
				var token_F = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[0]).slice(0,-5))
				console.log(token_F);
			}
			
			if (token_1.includes(substringG) === true){
				var token_G = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[1]).slice(0,-5))
				console.log(token_G);
			}
			if (token_1.includes(substringW) === true){
				var token_W = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[1]).slice(0,-5))
				console.log(token_W);
			}
			if (token_1.includes(substringF) === true){
				var token_F = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[1]).slice(0,-5))
				console.log(token_F);
			}
			
			if (token_2.includes(substringG) === true){
				var token_G = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[2]).slice(0,-5))
				console.log(token_G);
			}
			if (token_2.includes(substringW) === true){
				var token_W = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[2]).slice(0,-5))
				console.log(token_W);
			}
			if (token_2.includes(substringF) === true){
				var token_F = parseFloat((JSON.parse(xhr4.responseText).rows[0].balances[2]).slice(0,-5))
				console.log(token_F);
			}

**Comment by srisaard** [comment]
Done, please confirm the latest update.

**Comment by ghostprize** [comment]
Thank you
it work..

i donate to u
![Capture](https://user-images.githubusercontent.com/95231293/148538324-308f99df-6fc8-46bd-bbbe-2356e5d97ae4.PNG)
![thk](https://user-images.githubusercontent.com/95231293/148538363-e52a5fbe-d6c4-4fb9-ac33-6eb368d620f3.PNG)
