### ISSUE TITLE
api block

### ISSUE THREAD

**Issue by ghostprize** [srisaard/wax-farm-bot#7]
![block](https://user-images.githubusercontent.com/95231293/150647847-8cb6362e-a990-4703-ba64-930e5eb8ad21.PNG)
How can I solve this problem?

**Comment by srisaard** [comment]
I also search for the solution, if you found one please share it.

**Comment by ghostprize** [comment]
I opened multiple accounts thinking it was blocking too much from alcor.

**Comment by srisaard** [comment]
Just update to solve CORs problem, try the new version
