### ISSUE TITLE
How can I run this file

### ISSUE THREAD

**Issue by beomsookim1020** [srisaard/wax-farm-bot#8]
I'm not good at computer. I try really hard to run it but finally I can't reach to there.
I put my line token to .env file and I can't continue from here. I don't know how to run this scripts...

**Comment by srisaard** [comment]
If you aren't really need line notification, please try [officepandafarmbot.vercel.app](url)

**Comment by beomsookim1020** [comment]
I need line notification...
please teach me after step 3

**Comment by srisaard** [comment]
Now, you don't need to use .env. So please fill your token to webpage instead.
