### ISSUE TITLE
How to withdraw auto can you help me. 

### ISSUE THREAD

**Issue by pythonthailand** [srisaard/wax-farm-bot#9]
**This action notworking**      

        actions: [{
                account: 'farmersworld',
                name: 'withdraw',
                authorization: [{
                  actor: wax.userAccount,
                  permission: 'active',
                }],
                data: {
                  owner: wax.userAccount,
                  quantities: _quantity,
                  fee: _fee.fee
                },
              }]

**Comment by srisaard** [comment]
quantities should be 4decimals with "GOOD", "WOOD" or "FOOD.
Ex.
quantities: "1.5653 GOLD"
qunatities: "0.1000 FOOD"
